version: '3.7'

volumes:
  ts-db:

services:
  ts-postgres:
    container_name: dz1-db
    image: postgres:15.8-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dz1-db
    volumes:
      - ts-db:/var/lib/postgresql/data
#      - ./data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5438:5432"
